version: "3.8"
services:
  hazelcast1:
    image: hazelcast/hazelcast:5.4.0
    ports:
    - "5701:5701"
  hazelcast2:
    image: hazelcast/hazelcast:5.4.0
    ports:
    - "5702:5702"
  hazelcast3:
    image: hazelcast/hazelcast:5.4.0
    ports:
    - "5703:5703"
  management-center:
    image: hazelcast/management-center:latest-snapshot
    ports:
    - "8080:8080"
    environment:
    - MC_DEFAULT_CLUSTER=dev
    - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast1,hazelcast2,hazelcast3

